[package]
name = "todoist"
version = "0.1.0"
authors = ["Justin Simerly <justin.simerly@endress.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
serde_repr = "0.1"
